- CONTRIBUTORS.md
- packages/carbon-graphs/CHANGELOG.md
- packages/carbon-graphs/src/js/controls/Graph/Graph.js
- packages/carbon-graphs/tests/unit/controls/Graph/GraphResize-spec.js
Using resizeHandler in advanced graphing application throws a console error. 
To fix the error, we have to add a condition to check if the graphContainer is present and then resize the graph.
Closes #10 
Unit test
@cerner/terra
@cerner/carbon
> Fix: Resize Handler Console Error Fix (fixes #10)

- CONTRIBUTORS.md
- package.json
- packages/carbon-graphs/CHANGELOG.md
- packages/carbon-graphs/src/js/controls/PairedResult/PairedResult.js
- packages/carbon-graphs/tests/unit/controls/PairedResult/PairedResultLoad-spec.js
- packages/carbon-graphs/tests/unit/controls/PairedResult/PairedResultPanning-spec.js
- packages/terra-graphs/docs/contributing/README.md
- packages/terra-graphs/docs/controls/PairedResult.md
- With these changes paired result is now capable of handling null/blank/undefined during both initial load and reflow(by getting rid of those points passed by consumers).
Closes #11 
- In this issue, each case like high/low/medium as undefined/null/blank has been tested.
**Handling undefined during reflow:** 
**Before:**
- When undefined is passed as high during reflow we can see an error as shown in the image below.
**After:**
-  Due to changes made in this issue error got resolved.
**Handling null/blank during reflow:** 
- Previously, terra-graphs only handles undefined values as high/low/mid. Because of current changes terra-graphs now can handle null/blank values too as high/mid/low during both initial load and reflow by getting rid …
> Fix: Reflow does not accept Paired Result with low/high/mid value as undefined/null/blank

- packages/carbon-graphs/CHANGELOG.md
- packages/carbon-graphs/src/js/controls/PairedResult/helpers/helpers.js
- packages/carbon-graphs/tests/unit/controls/PairedResult/PairedResultLoad-spec.js
- packages/carbon-graphs/webpack/dev-server.js
1. Made changes in order to make terra-graphs work in Internet Explorer.
2. The connecting line does not go away for paired results when toggled off in IE. The line would disappear when either High or Low is toggled off in Chrome but not working as expected in IE. Changes made accordingly in this PR to fix the above issue.
Closes #20 
**Terra-Graphs in Internet Explorer.**
**Before**
**After**
**Paired result graph in Internet Explorer when high is toggled:**
**Before:**
**After:**
@cerner/terra
@cerner/carbon
> Fix: Connecting line does not go away for paired results when toggled off in IE

- packages/carbon-graphs/CHANGELOG.md
- packages/carbon-graphs/src/js/helpers/axis.js
- packages/carbon-graphs/tests/unit/controls/Graph/GraphAxes-spec.js
- packages/carbon-graphs/tests/unit/controls/Graph/GraphPanning-spec.js
This code change updates the logic for the y-axis container generation to be static instead of dynamic.
Closes #79 
Before:
After:
@cerner/terra
@cerner/carbon
> Fix: 79 - Updated Y-axis label width to be static

- packages/carbon-graphs/CHANGELOG.md
- packages/carbon-graphs/tests/unit/controls/Bar/BarPanning-spec.js
- packages/carbon-graphs/tests/unit/controls/Bar/BarPanningMultipleDatasets-spec.js
- packages/carbon-graphs/tests/unit/controls/Gantt/GanttPanning-spec.js
- packages/carbon-graphs/tests/unit/controls/Gantt/GanttPanningMultipleDatasets-spec.js
- packages/carbon-graphs/tests/unit/controls/Graph/GraphPanning-spec.js
- packages/carbon-graphs/tests/unit/controls/Graph/GraphPanningMultipleDatasets-spec.js
- packages/carbon-graphs/tests/unit/controls/Line/LinePanning-spec.js
- packages/carbon-graphs/tests/unit/controls/Line/LinePanningMultipleDatasets-spec.js
- packages/carbon-graphs/tests/unit/controls/PairedResult/PairedResultPanning-spec.js
- packages/carbon-graphs/tests/unit/controls/PairedResult/PairedResultPanningMultipleDatasets-spec.js
- packages/carbon-graphs/tests/unit/controls/Scatter/ScatterPanning-spec.js
- packages/carbon-graphs/tests/unit/controls/Scatter/ScatterPanningMultipleDatasets-spec.js
- packages/carbon-graphs/tests/unit/controls/Timeline/TimelinePanning-spec.js
- packages/carbon-graphs/tests/unit/controls/Timeline/TimelinePanningMultipleDatasets-spec.js
Currently, warnings in unit tests add spam to output and bury any failing tests. This PR updates tests so that warnings are suppressed.
Before:
After:
@cerner/terra
@cerner/carbon
> Chore: remove warnings from unit tests

- packages/carbon-graphs/CHANGELOG.md
- packages/carbon-graphs/src/js/controls/Bar/Bar.js
- packages/carbon-graphs/src/js/controls/Line/Line.js
- packages/carbon-graphs/src/js/controls/PairedResult/PairedResult.js
- packages/carbon-graphs/src/js/controls/Scatter/Scatter.js
- packages/carbon-graphs/src/js/helpers/label.js
- packages/carbon-graphs/tests/unit/controls/Bar/BarPanningMultipleDatasets-spec.js
- packages/carbon-graphs/tests/unit/controls/Line/LinePanningMultipleDatasets-spec.js
- packages/carbon-graphs/tests/unit/controls/PairedResult/PairedResultPanningMultipleDatasets-spec.js
- packages/carbon-graphs/tests/unit/controls/Scatter/ScatterPanningMultipleDatasets-spec.js
Y-axis icons and y2-axis icons not updating based on the values passed down to the reflow. If there is no data for a particular legend, the y-axis icon should hide and if there is data for a particular legend during panning, y-axis icons should display.
Closes #87 
@cerner/terra
@cerner/carbon
> Fixed Y-axis and y2-axis icons not updating during reflow

- packages/carbon-graphs/CHANGELOG.md
- packages/carbon-graphs/dev/app.less
- packages/carbon-graphs/src/js/controls/Timeline/Timeline.js
- packages/carbon-graphs/src/js/helpers/styles.js
- packages/carbon-graphs/src/less/core.less
- packages/carbon-graphs/tests/unit/controls/Timeline/Timeline-spec.js
- packages/carbon-graphs/tests/unit/controls/Timeline/TimelineLoad-spec.js
- Timeline graph only works if it is the first/only graph on a page. Changed the way the timeline graph access the ticks to fix this issue.
Closes #84 
- Wrote test case by reproducing the issue and testing the translate position of timeline graph.
@cerner/terra
@cerner/carbon
> Timeline graph only works if it is the first/only graph on a page

- package.json
- packages/carbon-graphs/CHANGELOG.md
- packages/carbon-graphs/src/js/core/BaseConfig/helper.js
- packages/carbon-graphs/tests/unit/controls/Graph/GraphDateline-spec.js
- Two Gantt instances on the same page are not fully isolated as they should be. This leads to strange effects such as collapsing sections of the first Gantt causes data on the second Gantt to be removed. 
- Fixed this by adding unique id to clippath.
Closes #98 
@cerner/terra
@cerner/carbon
> Fixed isolation of different graph instances in same page.

- packages/carbon-graphs/CHANGELOG.md
- packages/carbon-graphs/src/js/helpers/label.js
- packages/carbon-graphs/tests/unit/controls/Graph/GraphAxes-spec.js
- Fixed a bug that is causing UI glitch while redering graph with y2 axis by adding transform points for label shape container at the first place.
Closes #192  
- All tests are running successfully.
- Added a test case to test transform points at the first place.
@cerner/terra
@cerner/carbon
> Fixed a bug causing the UI glitch while rendering graphs having y2 axis.

- packages/carbon-graphs/CHANGELOG.md
- packages/carbon-graphs/src/js/controls/Gantt/Gantt.js
- packages/carbon-graphs/src/js/controls/Graph/Graph.js
- packages/carbon-graphs/src/js/controls/Graph/helpers/helpers.js
- packages/carbon-graphs/src/js/controls/Line/Line.js
- packages/carbon-graphs/src/js/controls/Timeline/Timeline.js
- packages/carbon-graphs/src/js/helpers/axis.js
- packages/carbon-graphs/tests/unit/controls/Graph/GraphAxes-spec.js
- packages/carbon-graphs/tests/unit/controls/Line/LineLoad-spec.js
This PR finishes implementation for the the `axis.x.allowCalibration` prop for a line graph.
Note: this feature is still a work in progress and will break if used for anything besides a line graph with a numerical x-axis. However, this is still a passive change since this feature needs to be explicitly toggled on. 
Closes #
@cerner/terra
@cerner/carbon
> Adding x-axis calibration for a numerical x-axis

- packages/carbon-graphs/CHANGELOG.md
- packages/carbon-graphs/src/js/controls/Graph/Graph.js
- packages/carbon-graphs/src/js/controls/Graph/helpers/helpers.js
- packages/carbon-graphs/src/js/controls/Line/Line.js
- packages/carbon-graphs/src/js/helpers/axis.js
- packages/carbon-graphs/src/js/helpers/utils.js
- packages/carbon-graphs/tests/unit/controls/Line/LineLoad-spec.js
This PR partially addresses UXPLATFORM-6904 by adding support for a timeseries axis for `config.axis.x.allowCalibration`. This is PR 1 of 2. PR #2 will add tests and documentation. 
Closes #
@cerner/terra
@cerner/carbon
> Add allowCalibration to the x-axis for a timeseries line graph (PR 1 of 2)

- packages/carbon-graphs/CHANGELOG.md
- packages/carbon-graphs/src/js/controls/Scatter/Scatter.js
- packages/carbon-graphs/tests/unit/controls/Scatter/ScatterLoad-spec.js
[UXPLATFORM-6842](https://jira2.cerner.com/browse/UXPLATFORM-6824)
===
Allows a scatter graph to be configured with the 'Allow Callibration' preference. This allows the user to see all the data points without it being cut off.
`npm run karma`
@cerner/terra
@cerner/carbon
> Scatter Graph - Update to support the allowXCallibration prop

- packages/carbon-graphs/CHANGELOG.md
- packages/carbon-graphs/src/js/controls/PairedResult/PairedResult.js
- packages/carbon-graphs/tests/unit/controls/PairedResult/PairedResultLoad-spec.js
This PR updates the paired result graph to support the axis.x.allowCalibration prop for a timeseries x-axis. (UXPLATFORM-6991)
@cerner/terra
@cerner/carbon
> Paired Result - Add x-axis calibration for timeseries x-axis

- packages/carbon-graphs/CHANGELOG.md
- packages/carbon-graphs/src/js/controls/Bar/Bar.js
- packages/carbon-graphs/tests/unit/controls/Bar/BarLoad-spec.js
[UXPLATFORM-6814](https://jira2.cerner.com/browse/UXPLATFORM-6814)
===
Allows a bar graph to be configured with the 'Allow Callibration' preference. This allows the user to see all the data points without it being cut off.
`npm run karma`
@cerner/terra
@cerner/carbon
> Bar Graph - Update to support the allowXCallibration prop

- packages/carbon-graphs/CHANGELOG.md
- packages/carbon-graphs/dev-site/serve/serve-static.js
- packages/carbon-graphs/src/js/helpers/axis.js
- packages/carbon-graphs/tests/unit/controls/Line/LinePanning-spec.js
- packages/carbon-graphs/webpack/dev-server.js
- webpack.config.js
**What was changed:**
Fixed infinite padding in line graphs on multiple unload/load where maximum datapoint is zero.
Added a check for maximum datapoint to make sure isRangeModified is returned correctly when no data is changed. Previous behavior is, it always returns true when maximum datapoint is zero. 
**Why it was changed:**
When the maximum datapoint on an y axis is 0, padding is added on every loadContent, so that when multiple unloads and loads occur, the datapoints are "squished". (See example in linked investigation.)
The reason this is happening is that when the max value is 0, [isRangeModified always evaluates to true](https://github.com/cerner/terra-graphs/blob/main/packages/carbon-graphs/src/js/helpers/axis.js#L1596), thus on every load padding is re-added.
UXPLATFORM-7542 …
> Fix infinite padding on multiple unload/load where maximum datapoint is zero

- packages/carbon-graphs/CHANGELOG.md
- packages/carbon-graphs/package.json
The terra-graphs was not working with terra-clinical:
**What was changed:**
"d3-dispatch" dependency was added.
**Why it was changed:**
It resolves the problem in terra-clinical:
> Transition error fix

- package.json
- packages/carbon-graphs/CHANGELOG.md
- packages/carbon-graphs/package.json
- packages/terra-graphs-docs/CHANGELOG.md
- packages/terra-graphs-docs/package.json
- @cerner/carbon-graphs@2.23.2
- @cerner/terra-graphs-docs@1.5.0
eslint-plugin-jsdoc version bump was needed to resolve eslint conflicts that prevented `npm i` from working.
> Release September 20th, 2023

- packages/carbon-graphs/CHANGELOG.md
- packages/carbon-graphs/package.json
Currently Clinical Detail view doesn't work due to transition error coming from d3.transition package.
The d3.transition version was unlocked to pull the latest change that doesn't have that error.
Carbon-graphs package with changes was created locally and terra-clinical pulled from that local package. **Note: for change to work with terra-clinical, carbon-graphs might need to be moved from dev dependencies to dependencies.**
It resolved the isuue and Clinical Detail view had no issues:
Tested changes locally for no issues with existing functionality:
> Unlock d3-transition

- packages/carbon-graphs/CHANGELOG.md
- packages/carbon-graphs/package.json
- packages/terra-graphs-docs/CHANGELOG.md
- packages/terra-graphs-docs/package.json
- @cerner/carbon-graphs@2.23.3
- @cerner/terra-graphs-docs@1.6.0
> Release September 26th, 2023

- packages/carbon-graphs/CHANGELOG.md
- packages/carbon-graphs/package.json
- packages/terra-graphs-docs/CHANGELOG.md
- packages/terra-graphs-docs/package.json
**What was changed:**
**Why it was changed:**
**This PR resolves:**
UXPLATFORM-XXXX 
---
@cerner/terra
> Release-1-4-2024
