cerner/terra-graphs

- dangerfile.js
- packages/terra-graphs/package.json
Ignore terra-graphs until we're ready to release. Additionally setup danger to ignore changelog updates on packages that are ignored by lerna.
Closes #
@cerner/terra
@cerner/carbon
> Ignore terra-graphs until we're ready to release.

- packages/terra-graphs/package.json
This change is needed to allow the release of the scoped package to the public npm repo
Closes #
@cerner/terra
@cerner/carbon
> Allow scoped package to be released publicly.

- packages/carbon-graphs/CHANGELOG.md
- packages/carbon-graphs/package.json
- Purpose of this PR is to release changes.
@cerner/terra
@cerner/carbon
> Minor release

- app.json
Lets get on a newer version of the heroku stack to stop heroku from emailing me.
Closes #
@cerner/terra
@cerner/carbon
> Update heroku stack version

- packages/carbon-graphs/CHANGELOG.md
- packages/carbon-graphs/package.json
- Purpose of this PR is to release changes.
@cerner/terra
@cerner/carbon
> Patch Release 2.16.1

- package.json
- packages/carbon-graphs/CHANGELOG.md
- packages/carbon-graphs/src/js/controls/Bubble/helpers/helpersMultipleDataset.js
- packages/carbon-graphs/src/js/controls/Bubble/helpers/helpersSingleDataset.js
- packages/carbon-graphs/tests/unit/controls/Gantt/GanttEventline-spec.js
Upgrade eslint and stylelint. I did not touch the overrides in this project but we should look at removing or scoping them to only carbon-graphs.
Closes #
@cerner/terra
@cerner/carbon
> Update eslint and stylelint

- packages/carbon-graphs/CHANGELOG.md
- packages/carbon-graphs/package.json
PR for release version 2.16.2
@cerner/terra
@cerner/carbon
> release update 2.16.2

- .github/ISSUE_TEMPLATE/BUG_REPORT.md
- .github/ISSUE_TEMPLATE/FEATURE_REQUEST.md
- Added codeSandBox template and labels to issue template.
@cerner/terra
@cerner/carbon
> Add codeSandBox template and labels to issue template.

- package.json
Fix for herkou PR deployments. The lerna init step isn't needed.
Closes #
@cerner/terra
@cerner/carbon
> Preemptively fix heroku pr deployment

- packages/carbon-graphs/CHANGELOG.md
- packages/carbon-graphs/package.json
Closes #
@cerner/terra
@cerner/carbon
> Release 2.16.3

- packages/terra-graphs/docs/helpers/Ticks.md
Updated the documentation for improved clarification of how Carbon handles ticks.
@cerner/terra
@cerner/carbon
> Updated Ticks.md

- .travis.yml
This PR removes redundant Travis jobs to reduce build times.
Closes #96 
@cerner/terra
@cerner/carbon
> Removed extra Travis jobs

- .github/CODEOWNERS
Closes #
@cerner/terra
@cerner/carbon
> [terra-graphs] Update CODEOWNERS

- packages/carbon-graphs/CHANGELOG.md
- packages/carbon-graphs/package.json
> Publish on 4-27-2021

- packages/carbon-graphs/CHANGELOG.md
- packages/carbon-graphs/package.json
- packages/terra-graphs-docs/CHANGELOG.md
- packages/terra-graphs-docs/package.json
Publish on 05-11-2021
@cerner/terra
@cerner/carbon
> Publish on 05-11-2021

- .github/ISSUE_TEMPLATE/STORY.md
Added new template for story based issues.
@cerner/terra
@cerner/carbon
> Added new story template

- packages/carbon-graphs/CHANGELOG.md
- packages/carbon-graphs/package.json
- packages/terra-graphs-docs/package.json
- Release 06-15-2021
@cerner/terra
@cerner/carbon
> Release on 06-15-2021

- packages/terra-graphs/CHANGELOG.md
- packages/terra-graphs/tests/wdio/Graphs/BarGraph/bar-graph-spec.js
- packages/terra-graphs/tests/wdio/Graphs/BubbleGraph/bubbleGraphs-spec.js
- packages/terra-graphs/tests/wdio/Graphs/CombinationGraph/combination-graph-spec.js
- packages/terra-graphs/tests/wdio/Graphs/GanttChart/gantt-chart-spec.js
- packages/terra-graphs/tests/wdio/Graphs/General/general-spec.js
- packages/terra-graphs/tests/wdio/Graphs/LineGraph/line-graph-spec.js
- packages/terra-graphs/tests/wdio/Graphs/PairedResultGraph/paired-result-graph-spec.js
- packages/terra-graphs/tests/wdio/Graphs/PieChart/pie-chart-spec.js
- packages/terra-graphs/tests/wdio/Graphs/ScatterGraph/scatter-graph-spec.js
- packages/terra-graphs/tests/wdio/Graphs/Timeline/timeline-spec.js
- Made changes to all WDIO test URL's according to terra rules.
Closes #161 
@cerner/terra
@cerner/carbon
> Made changes to WDIO test url

- .nvmrc
- package.json
Closes #77
@cerner/terra
@cerner/carbon
> updated node version to 12

- packages/terra-graphs-docs/CHANGELOG.md
- packages/terra-graphs-docs/src/terra-dev-site/doc/Graphs/Timeline/BasicTimeline/AxisWithNoTickValues.2.doc.mdx
- packages/terra-graphs-docs/src/terra-dev-site/doc/Graphs/Timeline/BasicTimeline/SimpleTimeline.1.doc.mdx
- packages/terra-graphs-docs/src/terra-dev-site/doc/Graphs/Timeline/Criticality/TimelineCriticality.1.doc.mdx
- packages/terra-graphs-docs/src/terra-dev-site/doc/Graphs/Timeline/Reflow/DynamicData.2.doc.mdx
- packages/terra-graphs-docs/src/terra-dev-site/doc/Graphs/Timeline/Reflow/SimplePanning.1.doc.mdx
- packages/terra-graphs-docs/src/terra-dev-site/doc/example/Graphs-Carbon/Timeline/BasicTimeline/AxisWithNoTickValues.jsx
- packages/terra-graphs-docs/src/terra-dev-site/doc/example/Graphs-Carbon/Timeline/BasicTimeline/SimpleTimeline.jsx
- packages/terra-graphs-docs/src/terra-dev-site/doc/example/Graphs-Carbon/Timeline/Criticality/TimelineCriticality.jsx
- packages/terra-graphs-docs/src/terra-dev-site/doc/example/Graphs-Carbon/Timeline/Reflow/DynamicData.jsx
- packages/terra-graphs-docs/src/terra-dev-site/doc/example/Graphs-Carbon/Timeline/Reflow/SimplePanning.jsx
- Made changes to the documentation for all Timeline graph examples to make the dev site carbon-centric.
Closes #173 
@cerner/terra
@cerner/carbon
> Updated timeline documentation and examples to be carbon centric

- packages/terra-graphs-docs/CHANGELOG.md
- packages/terra-graphs-docs/src/terra-dev-site/doc/Graphs/ScatterGraph/BasicScatterGraphs/SimpleScatter.1.doc.mdx
- packages/terra-graphs-docs/src/terra-dev-site/doc/Graphs/ScatterGraph/BasicScatterGraphs/Timeseries.2.doc.mdx
- packages/terra-graphs-docs/src/terra-dev-site/doc/Graphs/ScatterGraph/BasicScatterGraphs/TimeseriesWithDateline.3.doc.mdx
- packages/terra-graphs-docs/src/terra-dev-site/doc/Graphs/ScatterGraph/BasicScatterGraphs/TimeseriesWithEventline.4.doc.mdx
- packages/terra-graphs-docs/src/terra-dev-site/doc/Graphs/ScatterGraph/BasicScatterGraphs/Y2Axis.5.doc.mdx
- packages/terra-graphs-docs/src/terra-dev-site/doc/Graphs/ScatterGraph/Criticality/Simple.1.doc.mdx
- packages/terra-graphs-docs/src/terra-dev-site/doc/Graphs/ScatterGraph/Reflow/DynamicData.2.doc.mdx
- packages/terra-graphs-docs/src/terra-dev-site/doc/Graphs/ScatterGraph/Reflow/SimplePanning.1.doc.mdx
- packages/terra-graphs-docs/src/terra-dev-site/doc/example/Graphs-Carbon/ScatterGraph/BasicScatterGraphs/SimpleScatter.jsx
- packages/terra-graphs-docs/src/terra-dev-site/doc/example/Graphs-Carbon/ScatterGraph/BasicScatterGraphs/Timeseries.jsx
- packages/terra-graphs-docs/src/terra-dev-site/doc/example/Graphs-Carbon/ScatterGraph/BasicScatterGraphs/TimeseriesWithDateline.jsx
- packages/terra-graphs-docs/src/terra-dev-site/doc/example/Graphs-Carbon/ScatterGraph/BasicScatterGraphs/TimeseriesWithEventline.jsx
- packages/terra-graphs-docs/src/terra-dev-site/doc/example/Graphs-Carbon/ScatterGraph/BasicScatterGraphs/Y2Axis.jsx
- packages/terra-graphs-docs/src/terra-dev-site/doc/example/Graphs-Carbon/ScatterGraph/Criticality/Simple.jsx
- packages/terra-graphs-docs/src/terra-dev-site/doc/example/Graphs-Carbon/ScatterGraph/Reflow/DynamicData.jsx
- packages/terra-graphs-docs/src/terra-dev-site/doc/example/Graphs-Carbon/ScatterGraph/Reflow/SimplePanning.jsx
- Made changes to the documentation for all Scatter graph examples to make the dev site carbon-centric.
Closes #172 
@cerner/terra
@cerner/carbon
> Updated Scatter graph documentation and examples to be carbon-centric.

- .eslintrc.yaml
- packages/terra-graphs-docs/src/terra-dev-site/doc/example/Graphs-Carbon/LineGraph/Reflow/DynamicData.jsx
- packages/terra-graphs-docs/src/terra-dev-site/doc/example/Graphs-Carbon/LineGraph/Reflow/DynamicLegend.jsx
- packages/terra-graphs-docs/src/terra-dev-site/doc/example/Graphs-Carbon/LineGraph/Reflow/MultipleDatasets.jsx
- packages/terra-graphs-docs/src/terra-dev-site/doc/example/Graphs-Carbon/LineGraph/Reflow/SimplePanning.jsx
- packages/terra-graphs-docs/src/terra-dev-site/doc/example/Graphs-Carbon/LineGraph/Reflow/Y2Panning.jsx
- packages/terra-graphs-docs/src/terra-dev-site/doc/example/Graphs-Carbon/PairedResultGraph/Reflow/DynamicData.jsx
- packages/terra-graphs-docs/src/terra-dev-site/doc/example/Graphs-Carbon/PairedResultGraph/Reflow/DynamicEventline.jsx
- packages/terra-graphs-docs/src/terra-dev-site/doc/example/Graphs-Carbon/PairedResultGraph/Reflow/MultipleDatasetsWithY2Axis.jsx
- packages/terra-graphs-docs/src/terra-dev-site/doc/example/Graphs-Carbon/PairedResultGraph/Reflow/SimplePanning.jsx
- packages/terra-graphs-docs/src/terra-dev-site/doc/example/Graphs-Carbon/ScatterGraph/Reflow/DynamicData.jsx
- packages/terra-graphs-docs/src/terra-dev-site/doc/example/Graphs-Carbon/ScatterGraph/Reflow/SimplePanning.jsx
- packages/terra-graphs-docs/src/terra-dev-site/doc/example/Graphs/LineGraph/Reflow/DynamicEventline.jsx
- packages/terra-graphs-docs/src/terra-dev-site/doc/example/Graphs/ScatterGraph/Reflow/DynamicData.jsx
- packages/terra-graphs-docs/src/terra-dev-site/test/graphs/LineGraph/Reflow/DynamicData.test.jsx
- packages/terra-graphs-docs/src/terra-dev-site/test/graphs/LineGraph/Reflow/DynamicEventline.test.jsx
- packages/terra-graphs-docs/src/terra-dev-site/test/graphs/LineGraph/Reflow/DynamicLegend.test.jsx
- packages/terra-graphs-docs/src/terra-dev-site/test/graphs/LineGraph/Reflow/MultipleDatasets.test.jsx
- packages/terra-graphs-docs/src/terra-dev-site/test/graphs/LineGraph/Reflow/SimplePanning.test.jsx
- packages/terra-graphs-docs/src/terra-dev-site/test/graphs/LineGraph/Reflow/Y2Panning.test.jsx
- packages/terra-graphs-docs/src/terra-dev-site/test/graphs/ScatterGraph/Reflow/DynamicData.test.jsx
- packages/terra-graphs/CHANGELOG.md
- packages/terra-graphs/src/components/Bar/BarGraph.jsx
- packages/terra-graphs/src/components/Bubble/BubbleMultipleDataset.jsx
- packages/terra-graphs/src/components/Bubble/BubbleSingleDataset.jsx
- packages/terra-graphs/src/components/Gantt/GanttChart.jsx
- packages/terra-graphs/src/components/Line/LineGraph.jsx
- packages/terra-graphs/src/components/PairedResult/PairedResultGraph.jsx
Closes #185
@cerner/terra
@cerner/carbon
> updated components and reflow examples for consistency

- packages/terra-graphs-docs/CHANGELOG.md
- packages/terra-graphs-docs/src/terra-dev-site/doc/Graphs/Documentation/Contributing/ContributingGuide.1.doc.mdx
- packages/terra-graphs-docs/src/terra-dev-site/doc/Graphs/Documentation/Core/Colors.8.doc.mdx
- packages/terra-graphs-docs/src/terra-dev-site/doc/Graphs/Documentation/Core/Errors.10.doc.mdx
- packages/terra-graphs-docs/src/terra-dev-site/doc/Graphs/Documentation/Core/Locale.9.doc.mdx
- packages/terra-graphs-docs/src/terra-dev-site/doc/Graphs/Documentation/Core/Shapes.7.doc.mdx
Closes #159 
@cerner/terra
@cerner/carbon
> Moved Documentation: colors, shapes, errors and contributing guide

- packages/carbon-graphs/CHANGELOG.md
- packages/carbon-graphs/package.json
- Release on 08-17-2021
@cerner/terra
@cerner/carbon
> Release on 08-17-2021

- packages/carbon-graphs/CHANGELOG.md
- packages/carbon-graphs/package.json
- Release on 08-31-2021.
@cerner/terra
@cerner/carbon
> Release on 08-31-2021

- packages/carbon-graphs/CHANGELOG.md
- packages/carbon-graphs/package.json
- Release on 09-28-2021
@cerner/terra
@cerner/carbon
> Release on 09-28-2021

- .travis.yml
Update .travis.yml to fix docker issues
> Update .travis.yml to fix docker issues

- .github/CODEOWNERS
Add Ben to code owners and set up auto closing of issues
> Add Ben to code owners and set up auto closing of issues

- packages/carbon-graphs/CHANGELOG.md
- packages/carbon-graphs/package.json
Publish on 11-09-2021
Closes #
@cerner/terra
@cerner/carbon
> Publish on 11-09-2021

- packages/carbon-graphs/CHANGELOG.md
- packages/carbon-graphs/package.json
Release 11-16
Closes #
@cerner/terra
@cerner/carbon
> Release 11-16

- .nvmrc
- package.json
Closes #78
https://jira2.cerner.com/browse/UXPLATFORM-5467
@cerner/terra
@cerner/carbon
> Upgrade to node 14

- RELEASE.md
- lerna.json
- packages/carbon-graphs/CHANGELOG.md
- packages/carbon-graphs/package.json
- packages/terra-graphs-docs/CHANGELOG.md
- packages/terra-graphs-docs/package.json
- Release on 11-30-2021
@cerner/terra
@cerner/carbon
> release on 11-30-2021

- RELEASE.md
- packages/carbon-graphs/CHANGELOG.md
- packages/carbon-graphs/package.json
- packages/terra-graphs-docs/CHANGELOG.md
- packages/terra-graphs-docs/package.json
Publish terra-graphs-docs as a public package and release
Closes #
@cerner/terra
@cerner/carbon
> Publish terra-graphs-docs as a public package

- packages/terra-graphs-docs/CHANGELOG.md
- packages/terra-graphs-docs/src/terra-dev-site/graph/CoreConfiguration.b/Documentation/Panning.12.graph.mdx
- Added reflowMultipleDataset documentation in panning docs.
Closes # [UXPLATFORM-6046](https://jira2.cerner.com/browse/UXPLATFORM-6046)
@cerner/terra
@cerner/carbon
> [UXPLATFORM-6046]Added reflowMultipleDataset documentation in panning docs.

- packages/terra-graphs-docs/CHANGELOG.md
- packages/terra-graphs-docs/package.json
- @cerner/terra-graphs-docs@1.0.2
Closes #
@cerner/terra
@cerner/carbon
> publish on 12-14-2021

- packages/carbon-graphs/CHANGELOG.md
- packages/carbon-graphs/package.json
- packages/terra-graphs-docs/CHANGELOG.md
- packages/terra-graphs-docs/package.json
> Preparing releases.

- packages/carbon-graphs/CHANGELOG.md
- packages/carbon-graphs/package.json
- packages/terra-graphs-docs/CHANGELOG.md
- packages/terra-graphs-docs/package.json
- carbon-graph2@2.21.0
- terra-graphs-docs@2.21.0
> release prep

- packages/terra-graphs-docs/CHANGELOG.md
- packages/terra-graphs-docs/package.json
- @cerner/terra-graphs-docs@1.2.0
Closes #
@cerner/terra
@cerner/carbon
> Publish 06/07/2022

- packages/carbon-graphs/CHANGELOG.md
- packages/carbon-graphs/src/js/controls/Bubble/Bubble.js
- packages/carbon-graphs/src/js/controls/Bubble/BubbleMultipleDataset.js
- packages/carbon-graphs/src/js/controls/Bubble/BubbleSingleDataset.js
- packages/carbon-graphs/src/js/controls/Bubble/helpers/helpers.js
- packages/carbon-graphs/src/js/controls/Line/Line.js
- packages/carbon-graphs/src/js/controls/PairedResult/PairedResult.js
- packages/carbon-graphs/src/js/controls/Scatter/Scatter.js
- packages/carbon-graphs/src/js/helpers/axis.js
- packages/carbon-graphs/tests/unit/controls/Bubble/MultipleDataset/BubbleMultipleDatasetLoad-spec.js
- packages/carbon-graphs/tests/unit/controls/Bubble/SingleDataset/BubbleSingleDatasetLoad-spec.js
- packages/carbon-graphs/tests/unit/controls/Graph/GraphAxes-spec.js
- packages/carbon-graphs/tests/unit/controls/Line/LineLoad-spec.js
Closes #
This closes UXPLATFORM-8604
@cerner/terra
@cerner/carbon
> BubbleGraph - Add x-axis calibration for the x-axis

- packages/carbon-graphs/CHANGELOG.md
- packages/carbon-graphs/package.json
- packages/terra-graphs-docs/CHANGELOG.md
- packages/terra-graphs-docs/package.json
- @cerner/carbon-graphs@2.22.0
- @cerner/terra-graphs-docs@1.3.0
Closes #
@cerner/terra
@cerner/carbon
> Publish 09/13/2022

- packages/carbon-graphs/CHANGELOG.md
- packages/carbon-graphs/package.json
- packages/terra-graphs-docs/CHANGELOG.md
- packages/terra-graphs-docs/package.json
- @cerner/carbon-graphs@2.23.0
- @cerner/terra-graphs-docs@1.4.0
Closes #
@cerner/terra
@cerner/carbon
> Publish 01/03/2023

- packages/carbon-graphs/CHANGELOG.md
- packages/carbon-graphs/package.json
- packages/terra-graphs-docs/CHANGELOG.md
- packages/terra-graphs-docs/package.json
- @cerner/carbon-graphs@2.23.0
- @cerner/terra-graphs-docs@1.4.0
> Release 03/29/23

- .github/workflows/ci-cd.yml
Closes #
@cerner/terra
@cerner/carbon
> fixing deployment overriding

- package.json
This PR updates the `lint:js` script in the root level `package.json` so that the maximum number of eslint warnings is zero, so that our lint PR checks will fail when there are warnings.
This change is identical to https://github.com/cerner/terra-core/pull/3832.
Tested by running the lint script locally and as part of the PR check.
**This PR resolves:**
UXPLATFORM-9206 
---
@cerner/terra
> Update lint:js script

- packages/carbon-graphs/CHANGELOG.md
- packages/carbon-graphs/package.json
- packages/terra-graphs-docs/CHANGELOG.md
- packages/terra-graphs-docs/package.json
- @cerner/carbon-graphs@2.23.1
- @cerner/terra-graphs-docs@1.4.1
> Release Aug 21, 2023

- package-lock.json
- packages/carbon-graphs/CHANGELOG.md
- packages/carbon-graphs/package.json
- packages/terra-graphs-docs/CHANGELOG.md
- packages/terra-graphs-docs/package.json
- @cerner/carbon-graphs@2.25.0
- @cerner/terra-graphs-docs@1.9.0
> Release April 5

- packages/carbon-graphs/CHANGELOG.md
- packages/terra-graphs-docs/CHANGELOG.md
- packages/terra-graphs-docs/package.json
This PR fixes conflicting peer dependencies for terra-ui. 
---
@cerner/terra
> Terra UI fixes

- package-lock.json
- packages/terra-graphs-docs/CHANGELOG.md
- packages/terra-graphs-docs/package.json
- @cerner/terra-graphs-docs@1.9.1
> Release april 9

- package-lock.json
- packages/terra-graphs-docs/CHANGELOG.md
- packages/terra-graphs-docs/package.json
This PR adds missing files in the published packages.
**This PR resolves:**
UXPLATFORM-XXXX 
---
@cerner/terra
> [terra-graphs-docs] Add missing files

- packages/terra-graphs-docs/CHANGELOG.md
- packages/terra-graphs-docs/src/terra-dev-site/graph/example/Graphs-Carbon/Timeline/Reflow/DynamicData.jsx
- packages/terra-graphs-docs/src/terra-dev-site/graph/example/Graphs/Timeline/Reflow/DynamicData.jsx
- packages/terra-graphs-docs/src/terra-dev-site/test/graphs/Timeline/Reflow/DynamicData.test.jsx
This PR fixes some invalid imports in terra-graphs-docs.
**This PR resolves:**
UXPLATFORM-XXXX 
---
@cerner/terra
> [terra-graphs-docs] fix imports

- package-lock.json
- packages/terra-graphs-docs/CHANGELOG.md
- packages/terra-graphs-docs/package.json
- @cerner/terra-graphs-docs@1.9.3
> Release April 8 [3]
